name: CI

on:
  pull_request:
    branches: ["master"]

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
            enable-cache: true

      - name: Install dependencies and tools (use `uv sync`)
        run: |
          uv sync

      - name: Run tests
        working-directory: book_lib
        run: |
          mkdir -p results
          uv run pytest -n auto --junitxml=results/junit.xml --cov=books --cov-report=xml:results/coverage.xml --cov-report=html:results/coverage_html || true

      - name: Upload JUnit XML
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: junit-xml
          path: book_lib/results/junit.xml

      - name: Upload coverage xml
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml
          path: book_lib/results/coverage.xml

      - name: Upload coverage HTML
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-html
          path: book_lib/results/coverage_html

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: ${{ !cancelled() }}
        with:
          files: book_lib/results/junit.xml
